-- Generated by scripts/snapshot.sh. Do not edit.
-- Source of truth: supabase/migrations/



SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "app_handibaby";


ALTER SCHEMA "app_handibaby" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "app_handibaby"."correct_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_previous" "jsonb", "p_written_at" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
    if p_loser_score < 0 or p_loser_score > 9 then
        raise exception 'Invalid loser score: %', p_loser_score;
    end if;

    if p_winning_side not in ('blue', 'white') then
        raise exception 'Invalid winning side: %', p_winning_side;
    end if;

    insert into app_handibaby.scores_journal (
        entry_id,
        tournament_public_id,
        phase,
        duel,
        rank_in_duel,
        operation,
        winning_side,
        loser_score,
        previous,
        written_at
    ) values (
        p_journal_entry_id,
        p_tournament_public_id,
        p_phase,
        p_duel,
        p_rank_in_duel,
        'correct',
        p_winning_side,
        p_loser_score,
        p_previous,
        p_written_at
    )
    on conflict (entry_id) do nothing;

    insert into app_handibaby.matches (
        tournament_public_id,
        phase,
        duel,
        rank_in_duel,
        winning_side,
        loser_score,
        entered_at
    ) values (
        p_tournament_public_id,
        p_phase,
        p_duel,
        p_rank_in_duel,
        p_winning_side,
        p_loser_score,
        p_written_at
    )
    on conflict (tournament_public_id, phase, duel, rank_in_duel)
    do update set
        winning_side = excluded.winning_side,
        loser_score = excluded.loser_score,
        entered_at = excluded.entered_at;
end;
$$;


ALTER FUNCTION "app_handibaby"."correct_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_previous" "jsonb", "p_written_at" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "app_handibaby"."record_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_written_at" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
    if p_loser_score < 0 or p_loser_score > 9 then
        raise exception 'Invalid loser score: %', p_loser_score;
    end if;

    if p_winning_side not in ('blue', 'white') then
        raise exception 'Invalid winning side: %', p_winning_side;
    end if;

    insert into app_handibaby.scores_journal (
        entry_id,
        tournament_public_id,
        phase,
        duel,
        rank_in_duel,
        operation,
        winning_side,
        loser_score,
        previous,
        written_at
    ) values (
        p_journal_entry_id,
        p_tournament_public_id,
        p_phase,
        p_duel,
        p_rank_in_duel,
        'record',
        p_winning_side,
        p_loser_score,
        null,
        p_written_at
    )
    on conflict (entry_id) do nothing;

    insert into app_handibaby.matches (
        tournament_public_id,
        phase,
        duel,
        rank_in_duel,
        winning_side,
        loser_score,
        entered_at
    ) values (
        p_tournament_public_id,
        p_phase,
        p_duel,
        p_rank_in_duel,
        p_winning_side,
        p_loser_score,
        p_written_at
    )
    on conflict (tournament_public_id, phase, duel, rank_in_duel)
    do update set
        winning_side = excluded.winning_side,
        loser_score = excluded.loser_score,
        entered_at = excluded.entered_at;
end;
$$;


ALTER FUNCTION "app_handibaby"."record_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_written_at" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "app_handibaby"."save_player"("p_first_name" "text", "p_last_name" "text", "p_name_key" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
    insert into app_handibaby.players (
        first_name,
        last_name,
        name_key
    ) values (
        p_first_name,
        p_last_name,
        p_name_key
    )
    on conflict (name_key)
    do update set
        first_name = excluded.first_name,
        last_name = excluded.last_name;
end;
$$;


ALTER FUNCTION "app_handibaby"."save_player"("p_first_name" "text", "p_last_name" "text", "p_name_key" "text") OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "app_handibaby"."save_tournament"("p_public_id" "text", "p_label" "text", "p_start_date" "text", "p_status" "text", "p_passphrase_hash" "text", "p_created_at" bigint) RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
    insert into app_handibaby.tournaments (
        public_id,
        label,
        start_date,
        status,
        passphrase_hash,
        created_at
    ) values (
        p_public_id,
        p_label,
        p_start_date,
        p_status,
        p_passphrase_hash,
        p_created_at
    )
    on conflict (public_id)
    do update set
        label = excluded.label,
        start_date = excluded.start_date,
        status = excluded.status,
        passphrase_hash = excluded.passphrase_hash;
end;
$$;


ALTER FUNCTION "app_handibaby"."save_tournament"("p_public_id" "text", "p_label" "text", "p_start_date" "text", "p_status" "text", "p_passphrase_hash" "text", "p_created_at" bigint) OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "app_handibaby"."sync_tournament_bundle"("p_tournament" "jsonb", "p_players" "jsonb" DEFAULT '[]'::"jsonb", "p_tournament_players" "jsonb" DEFAULT '[]'::"jsonb", "p_teams" "jsonb" DEFAULT '[]'::"jsonb", "p_matches" "jsonb" DEFAULT '[]'::"jsonb", "p_frozen_edition" "jsonb" DEFAULT NULL::"jsonb") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
declare
    v_player jsonb;
    v_tp jsonb;
    v_team jsonb;
    v_match jsonb;
    v_public_id text;
begin
    v_public_id := p_tournament->>'public_id';
    if v_public_id is null or v_public_id = '' then
        raise exception 'Missing tournament public_id';
    end if;

    -- Upsert tournament
    insert into app_handibaby.tournaments (
        public_id,
        label,
        start_date,
        status,
        passphrase_hash,
        created_at
    ) values (
        v_public_id,
        coalesce(p_tournament->>'label', 'Tournoi'),
        coalesce(p_tournament->>'start_date', to_char(now(), 'YYYY-MM-DD')),
        coalesce(p_tournament->>'status', 'draft'),
        coalesce(p_tournament->>'passphrase_hash', ''),
        coalesce((p_tournament->>'created_at')::bigint, (extract(epoch from now()) * 1000)::bigint)
    )
    on conflict (public_id)
    do update set
        label = excluded.label,
        start_date = excluded.start_date,
        status = excluded.status,
        passphrase_hash = excluded.passphrase_hash;

    -- Upsert players
    if p_players is not null and p_players != 'null'::jsonb then
        for v_player in select * from jsonb_array_elements(p_players)
        loop
            insert into app_handibaby.players (
                first_name,
                last_name,
                name_key
            ) values (
                v_player->>'first_name',
                v_player->>'last_name',
                v_player->>'name_key'
            )
            on conflict (name_key)
            do update set
                first_name = excluded.first_name,
                last_name = excluded.last_name;
        end loop;
    end if;

    -- Upsert tournament players
    if p_tournament_players is not null and p_tournament_players != 'null'::jsonb then
        for v_tp in select * from jsonb_array_elements(p_tournament_players)
        loop
            insert into app_handibaby.tournament_players (
                tournament_public_id,
                player_name_key
            ) values (
                v_public_id,
                v_tp->>'player_name_key'
            )
            on conflict (tournament_public_id, player_name_key) do nothing;
        end loop;
    end if;

    -- Upsert teams
    if p_teams is not null and p_teams != 'null'::jsonb then
        for v_team in select * from jsonb_array_elements(p_teams)
        loop
            insert into app_handibaby.teams (
                tournament_public_id,
                label,
                player_one_name_key,
                player_two_name_key,
                team_index
            ) values (
                v_public_id,
                coalesce(v_team->>'label', 'Équipe'),
                v_team->>'player_one_name_key',
                v_team->>'player_two_name_key',
                (v_team->>'team_index')::integer
            )
            on conflict (tournament_public_id, team_index)
            do update set
                label = excluded.label,
                player_one_name_key = excluded.player_one_name_key,
                player_two_name_key = excluded.player_two_name_key;
        end loop;
    end if;

    -- Upsert matches
    if p_matches is not null and p_matches != 'null'::jsonb then
        for v_match in select * from jsonb_array_elements(p_matches)
        loop
            insert into app_handibaby.matches (
                tournament_public_id,
                phase,
                duel,
                rank_in_duel,
                winning_side,
                loser_score,
                entered_at
            ) values (
                v_public_id,
                v_match->>'phase',
                (v_match->>'duel')::integer,
                (v_match->>'rank_in_duel')::integer,
                v_match->>'winning_side',
                (v_match->>'loser_score')::integer,
                (v_match->>'entered_at')::bigint
            )
            on conflict (tournament_public_id, phase, duel, rank_in_duel)
            do update set
                winning_side = excluded.winning_side,
                loser_score = excluded.loser_score,
                entered_at = excluded.entered_at;
        end loop;
    end if;

    -- Upsert frozen edition if present
    if p_frozen_edition is not null and p_frozen_edition != 'null'::jsonb then
        insert into app_handibaby.frozen_editions (
            tournament_public_id,
            data,
            frozen_at
        ) values (
            v_public_id,
            p_frozen_edition->'data',
            coalesce((p_frozen_edition->>'frozen_at')::bigint, (extract(epoch from now()) * 1000)::bigint)
        )
        on conflict (tournament_public_id)
        do update set
            data = excluded.data,
            frozen_at = excluded.frozen_at;
    end if;
end;
$$;


ALTER FUNCTION "app_handibaby"."sync_tournament_bundle"("p_tournament" "jsonb", "p_players" "jsonb", "p_tournament_players" "jsonb", "p_teams" "jsonb", "p_matches" "jsonb", "p_frozen_edition" "jsonb") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "app_handibaby"."frozen_editions" (
    "tournament_public_id" "text" NOT NULL,
    "data" "jsonb" NOT NULL,
    "frozen_at" bigint NOT NULL
);


ALTER TABLE "app_handibaby"."frozen_editions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "app_handibaby"."matches" (
    "id" bigint NOT NULL,
    "tournament_public_id" "text" NOT NULL,
    "phase" "text" NOT NULL,
    "duel" integer,
    "rank_in_duel" integer,
    "winning_side" "text",
    "loser_score" integer,
    "entered_at" bigint
);


ALTER TABLE "app_handibaby"."matches" OWNER TO "postgres";


ALTER TABLE "app_handibaby"."matches" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "app_handibaby"."matches_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "app_handibaby"."players" (
    "id" bigint NOT NULL,
    "first_name" "text" NOT NULL,
    "last_name" "text" NOT NULL,
    "name_key" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "app_handibaby"."players" OWNER TO "postgres";


ALTER TABLE "app_handibaby"."players" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "app_handibaby"."players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "app_handibaby"."scores_journal" (
    "entry_id" "text" NOT NULL,
    "tournament_public_id" "text" NOT NULL,
    "phase" "text" NOT NULL,
    "duel" integer,
    "rank_in_duel" integer,
    "operation" "text" NOT NULL,
    "winning_side" "text" NOT NULL,
    "loser_score" integer NOT NULL,
    "previous" "jsonb",
    "written_at" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "timezone"('utc'::"text", "now"()) NOT NULL
);


ALTER TABLE "app_handibaby"."scores_journal" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "app_handibaby"."teams" (
    "id" bigint NOT NULL,
    "tournament_public_id" "text" NOT NULL,
    "label" "text" NOT NULL,
    "player_one_name_key" "text" NOT NULL,
    "player_two_name_key" "text" NOT NULL,
    "team_index" integer NOT NULL
);


ALTER TABLE "app_handibaby"."teams" OWNER TO "postgres";


ALTER TABLE "app_handibaby"."teams" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "app_handibaby"."teams_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "app_handibaby"."tournament_players" (
    "id" bigint NOT NULL,
    "tournament_public_id" "text" NOT NULL,
    "player_name_key" "text" NOT NULL
);


ALTER TABLE "app_handibaby"."tournament_players" OWNER TO "postgres";


ALTER TABLE "app_handibaby"."tournament_players" ALTER COLUMN "id" ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME "app_handibaby"."tournament_players_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "app_handibaby"."tournaments" (
    "public_id" "text" NOT NULL,
    "label" "text" NOT NULL,
    "start_date" "text" NOT NULL,
    "status" "text" DEFAULT 'draft'::"text" NOT NULL,
    "passphrase_hash" "text" NOT NULL,
    "created_at" bigint NOT NULL
);


ALTER TABLE "app_handibaby"."tournaments" OWNER TO "postgres";


ALTER TABLE ONLY "app_handibaby"."frozen_editions"
    ADD CONSTRAINT "frozen_editions_pkey" PRIMARY KEY ("tournament_public_id");



ALTER TABLE ONLY "app_handibaby"."matches"
    ADD CONSTRAINT "matches_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "app_handibaby"."matches"
    ADD CONSTRAINT "matches_unique_slot" UNIQUE NULLS NOT DISTINCT ("tournament_public_id", "phase", "duel", "rank_in_duel");



ALTER TABLE ONLY "app_handibaby"."players"
    ADD CONSTRAINT "players_name_key_key" UNIQUE ("name_key");



ALTER TABLE ONLY "app_handibaby"."players"
    ADD CONSTRAINT "players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "app_handibaby"."scores_journal"
    ADD CONSTRAINT "scores_journal_pkey" PRIMARY KEY ("entry_id");



ALTER TABLE ONLY "app_handibaby"."teams"
    ADD CONSTRAINT "teams_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "app_handibaby"."teams"
    ADD CONSTRAINT "teams_tournament_public_id_team_index_key" UNIQUE ("tournament_public_id", "team_index");



ALTER TABLE ONLY "app_handibaby"."tournament_players"
    ADD CONSTRAINT "tournament_players_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "app_handibaby"."tournament_players"
    ADD CONSTRAINT "tournament_players_tournament_public_id_player_name_key_key" UNIQUE ("tournament_public_id", "player_name_key");



ALTER TABLE ONLY "app_handibaby"."tournaments"
    ADD CONSTRAINT "tournaments_pkey" PRIMARY KEY ("public_id");



ALTER TABLE ONLY "app_handibaby"."frozen_editions"
    ADD CONSTRAINT "frozen_editions_tournament_public_id_fkey" FOREIGN KEY ("tournament_public_id") REFERENCES "app_handibaby"."tournaments"("public_id") ON DELETE CASCADE;



ALTER TABLE ONLY "app_handibaby"."teams"
    ADD CONSTRAINT "teams_player_one_name_key_fkey" FOREIGN KEY ("player_one_name_key") REFERENCES "app_handibaby"."players"("name_key");



ALTER TABLE ONLY "app_handibaby"."teams"
    ADD CONSTRAINT "teams_player_two_name_key_fkey" FOREIGN KEY ("player_two_name_key") REFERENCES "app_handibaby"."players"("name_key");



ALTER TABLE ONLY "app_handibaby"."teams"
    ADD CONSTRAINT "teams_tournament_public_id_fkey" FOREIGN KEY ("tournament_public_id") REFERENCES "app_handibaby"."tournaments"("public_id") ON DELETE CASCADE;



ALTER TABLE ONLY "app_handibaby"."tournament_players"
    ADD CONSTRAINT "tournament_players_player_name_key_fkey" FOREIGN KEY ("player_name_key") REFERENCES "app_handibaby"."players"("name_key") ON DELETE CASCADE;



ALTER TABLE ONLY "app_handibaby"."tournament_players"
    ADD CONSTRAINT "tournament_players_tournament_public_id_fkey" FOREIGN KEY ("tournament_public_id") REFERENCES "app_handibaby"."tournaments"("public_id") ON DELETE CASCADE;



CREATE POLICY "Public read frozen editions" ON "app_handibaby"."frozen_editions" FOR SELECT USING (true);



CREATE POLICY "Public read matches" ON "app_handibaby"."matches" FOR SELECT USING (true);



CREATE POLICY "Public read players" ON "app_handibaby"."players" FOR SELECT USING (true);



CREATE POLICY "Public read scores journal" ON "app_handibaby"."scores_journal" FOR SELECT USING (true);



CREATE POLICY "Public read teams" ON "app_handibaby"."teams" FOR SELECT USING (true);



CREATE POLICY "Public read tournament players" ON "app_handibaby"."tournament_players" FOR SELECT USING (true);



CREATE POLICY "Public read tournaments" ON "app_handibaby"."tournaments" FOR SELECT USING (true);



ALTER TABLE "app_handibaby"."frozen_editions" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."matches" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."scores_journal" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."teams" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."tournament_players" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "app_handibaby"."tournaments" ENABLE ROW LEVEL SECURITY;


GRANT USAGE ON SCHEMA "app_handibaby" TO "anon";
GRANT USAGE ON SCHEMA "app_handibaby" TO "authenticated";
GRANT USAGE ON SCHEMA "app_handibaby" TO "service_role";



GRANT ALL ON FUNCTION "app_handibaby"."correct_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_previous" "jsonb", "p_written_at" bigint) TO "anon";
GRANT ALL ON FUNCTION "app_handibaby"."correct_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_previous" "jsonb", "p_written_at" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "app_handibaby"."correct_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_previous" "jsonb", "p_written_at" bigint) TO "service_role";



GRANT ALL ON FUNCTION "app_handibaby"."record_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_written_at" bigint) TO "anon";
GRANT ALL ON FUNCTION "app_handibaby"."record_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_written_at" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "app_handibaby"."record_score"("p_journal_entry_id" "text", "p_tournament_public_id" "text", "p_phase" "text", "p_duel" integer, "p_rank_in_duel" integer, "p_winning_side" "text", "p_loser_score" integer, "p_written_at" bigint) TO "service_role";



GRANT ALL ON FUNCTION "app_handibaby"."save_player"("p_first_name" "text", "p_last_name" "text", "p_name_key" "text") TO "anon";
GRANT ALL ON FUNCTION "app_handibaby"."save_player"("p_first_name" "text", "p_last_name" "text", "p_name_key" "text") TO "authenticated";
GRANT ALL ON FUNCTION "app_handibaby"."save_player"("p_first_name" "text", "p_last_name" "text", "p_name_key" "text") TO "service_role";



GRANT ALL ON FUNCTION "app_handibaby"."save_tournament"("p_public_id" "text", "p_label" "text", "p_start_date" "text", "p_status" "text", "p_passphrase_hash" "text", "p_created_at" bigint) TO "anon";
GRANT ALL ON FUNCTION "app_handibaby"."save_tournament"("p_public_id" "text", "p_label" "text", "p_start_date" "text", "p_status" "text", "p_passphrase_hash" "text", "p_created_at" bigint) TO "authenticated";
GRANT ALL ON FUNCTION "app_handibaby"."save_tournament"("p_public_id" "text", "p_label" "text", "p_start_date" "text", "p_status" "text", "p_passphrase_hash" "text", "p_created_at" bigint) TO "service_role";



GRANT ALL ON FUNCTION "app_handibaby"."sync_tournament_bundle"("p_tournament" "jsonb", "p_players" "jsonb", "p_tournament_players" "jsonb", "p_teams" "jsonb", "p_matches" "jsonb", "p_frozen_edition" "jsonb") TO "anon";
GRANT ALL ON FUNCTION "app_handibaby"."sync_tournament_bundle"("p_tournament" "jsonb", "p_players" "jsonb", "p_tournament_players" "jsonb", "p_teams" "jsonb", "p_matches" "jsonb", "p_frozen_edition" "jsonb") TO "authenticated";
GRANT ALL ON FUNCTION "app_handibaby"."sync_tournament_bundle"("p_tournament" "jsonb", "p_players" "jsonb", "p_tournament_players" "jsonb", "p_teams" "jsonb", "p_matches" "jsonb", "p_frozen_edition" "jsonb") TO "service_role";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."frozen_editions" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."frozen_editions" TO "anon";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."matches" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."matches" TO "anon";



GRANT SELECT,USAGE ON SEQUENCE "app_handibaby"."matches_id_seq" TO "authenticated";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."players" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."players" TO "anon";



GRANT SELECT,USAGE ON SEQUENCE "app_handibaby"."players_id_seq" TO "authenticated";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."scores_journal" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."scores_journal" TO "anon";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."teams" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."teams" TO "anon";



GRANT SELECT,USAGE ON SEQUENCE "app_handibaby"."teams_id_seq" TO "authenticated";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."tournament_players" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."tournament_players" TO "anon";



GRANT SELECT,USAGE ON SEQUENCE "app_handibaby"."tournament_players_id_seq" TO "authenticated";



GRANT SELECT,INSERT,DELETE,UPDATE ON TABLE "app_handibaby"."tournaments" TO "authenticated";
GRANT SELECT ON TABLE "app_handibaby"."tournaments" TO "anon";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "app_handibaby" GRANT SELECT,USAGE ON SEQUENCES TO "authenticated";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "app_handibaby" GRANT SELECT,INSERT,DELETE,UPDATE ON TABLES TO "authenticated";




