#!/usr/bin/env bash
# Regenerates apps/<app>/schema.sql: a readable dump of the app's current schema.
# Reference only. supabase/migrations/ stays the source of truth.
set -euo pipefail
. "$(dirname "$0")/lib.sh"
load_env

app=${1:-}
[[ -n $app ]] || die "usage: $0 <app-slug>"
require_app "$app"

schema=$(schema_of "$app")
out="$ROOT/apps/$app/schema.sql"
tmp=$(mktemp)
trap 'rm -f "$tmp"' EXIT

cd "$ROOT"
supa db dump --linked --schema "$schema" -f "$tmp"
{
  echo "-- Generated by scripts/snapshot.sh. Do not edit."
  echo "-- Source of truth: supabase/migrations/"
  cat "$tmp"
} > "$out"
echo "${out#"$ROOT"/}"
